//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aporte> Aportes { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Registro> Registroes { get; set; }
        public virtual DbSet<Voluntario> Voluntarios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<rptAporteVoluntario_Result> rptAporteVoluntario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptAporteVoluntario_Result>("rptAporteVoluntario");
        }
    
        public virtual ObjectResult<rptCategoriasVoluntariado_Result> rptCategoriasVoluntariado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptCategoriasVoluntariado_Result>("rptCategoriasVoluntariado");
        }
    
        public virtual ObjectResult<rptSexoVoluntario_Result> rptSexoVoluntario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptSexoVoluntario_Result>("rptSexoVoluntario");
        }
    
        public virtual ObjectResult<rptGenero_Result> rptGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptGenero_Result>("rptGenero");
        }
    
        public virtual ObjectResult<rptCategoria_Result> rptCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptCategoria_Result>("rptCategoria");
        }
    
        public virtual ObjectResult<rptAporte_Result> rptAporte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptAporte_Result>("rptAporte");
        }
    
        public virtual ObjectResult<rptCatV_Result> rptCatV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptCatV_Result>("rptCatV");
        }
    
        public virtual ObjectResult<rptSexo_Result> rptSexo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptSexo_Result>("rptSexo");
        }
    
        public virtual ObjectResult<rptAgrupadoAporte_Result> rptAgrupadoAporte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptAgrupadoAporte_Result>("rptAgrupadoAporte");
        }
    
        public virtual ObjectResult<rptAgrupadoEventoGenero_Result> rptAgrupadoEventoGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptAgrupadoEventoGenero_Result>("rptAgrupadoEventoGenero");
        }
    }
}
