//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aporte> Aportes { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Registro> Registroes { get; set; }
        public virtual DbSet<Voluntario> Voluntarios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<rptAporteVoluntario_Result> rptAporteVoluntario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptAporteVoluntario_Result>("rptAporteVoluntario");
        }
    
        public virtual ObjectResult<rptCategoriasVoluntariado_Result> rptCategoriasVoluntariado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptCategoriasVoluntariado_Result>("rptCategoriasVoluntariado");
        }
    
        public virtual ObjectResult<rptSexoVoluntario_Result> rptSexoVoluntario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptSexoVoluntario_Result>("rptSexoVoluntario");
        }
    }
}
