//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registro
    {
        [ScaffoldColumn(false)]
        public int idregistro { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [Display(Name = "Fecha de Registro")]
        public Nullable<System.DateTime> fecha { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El estado es requerido"), MaxLength(55)]
        [Display(Name = "Estado")]
        public string estado { get; set; }
        public Nullable<int> idvoluntario { get; set; }
        public Nullable<int> idevento { get; set; }
        public Nullable<int> idaporte { get; set; }
    
        public virtual Aporte Aporte { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Voluntario Voluntario { get; set; }
    }
}
